[package]
name = "m-api"
description.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
reqwest = "0.12"
scraper = "0.23"
thiserror = "2"
tokio = { version = "1.45", features = ["macros"] }
